
name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'

jobs:
  package:
    name: Build and Package Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Package
      run: mvn -B clean package -DskipTests=true
    
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Maven Test
      run: mvn -B test

  deploy:
    name: Simulando Deploy
    needs: [ package, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Print Deploy Message
        run: echo "Deploy realizado com sucesso" 
