
name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'

  workflow_dispatch:

jobs:
  package:
    name: Build and Package Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Package
      run: mvn -B clean package -DskipTests=true

  call_lint_and_test:
    name: Lint and Test
    uses: ./.github/workflows/lint-and-test.yml
    with:
      java-version: '21'  
      
  ddeploy:
    name: Simulando Deploy
    needs: [ package, call_lint_and_test ]
    runs-on: ubuntu-latest
    steps:
      - name: Print Deploy Message
        run: echo "Deploy realizado com sucesso"
