name: self-hosted.yml
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-on-self-hosted:
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar versão do Java instalada
        run: |
          echo "A versão do Java é:"
          java -version
          echo "------------------------"

      - name: Instalar software
        run: |
          choco install maven -y

      - name: Usar o software instalado
        run: |
          refreshenv
          echo "Executando maven"
          mvn -v