name: variables-secrets.yml
on:
  workflow_dispatch:

jobs:
  variables_secrets:
    name: Demonstrar o uso de Vars e Secrets
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Variáveis
        run: |
          echo "Este workflow roda no modo: ${{ vars.APP_MODE }}"
          echo "Problemas, contate: ${{ vars.SUPPORT_EMAIL }}"

      - name: Condicional
        if: vars.APP_MODE == 'development'
        env:
          DEPLOY_TOKEN: ${{ secrets.PROD_TOKEN }}
        run: | 
          echo "Token Secret"
          echo $env:DEPLOY_TOKEN